name: test paytr

on:push

jobs:
  test-app:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      uses: actions/setup-node@v1
      with:
        node-version : '12.16.1'
    - run: npm ci
    - run: npm test
